var	testHotRec={
		chinese:[
			{describe:'[华语1]毕业季、回忆过去&追梦未来',url:'images/hot_rec/华语 (1).png'},
			{describe:'[华语2]毕业季、回忆过去&追梦未来',url:'images/hot_rec/华语 (2).png'},
			{describe:'[华语3]毕业季、回忆过去&追梦未来',url:'images/hot_rec/华语 (3).png'},
			{describe:'[华语4]毕业季、回忆过去&追梦未来',url:'images/hot_rec/华语 (4).png'},
			{describe:'[华语5]毕业季、回忆过去&追梦未来',url:'images/hot_rec/华语 (5).png'},
			{describe:'[华语6]毕业季、回忆过去&追梦未来',url:'images/hot_rec/华语 (6).png'},
			{describe:'[华语7]毕业季、回忆过去&追梦未来',url:'images/hot_rec/华语 (7).png'},
			{describe:'[华语8]毕业季、回忆过去&追梦未来',url:'images/hot_rec/华语 (8).png'},
		],
		popular:[
			{describe:'[流行1]毕业季、回忆过去&追梦未来',url:'images/hot_rec/流行 (1).png'},
			{describe:'[流行2]毕业季、回忆过去&追梦未来',url:'images/hot_rec/流行 (2).png'},
			{describe:'[流行3]毕业季、回忆过去&追梦未来',url:'images/hot_rec/流行 (3).png'},
			{describe:'[流行4]毕业季、回忆过去&追梦未来',url:'images/hot_rec/流行 (4).png'},
			{describe:'[流行5]毕业季、回忆过去&追梦未来',url:'images/hot_rec/流行 (5).png'},
			{describe:'[流行6]毕业季、回忆过去&追梦未来',url:'images/hot_rec/流行 (6).png'},
			{describe:'[流行7]毕业季、回忆过去&追梦未来',url:'images/hot_rec/流行 (7).png'},
			{describe:'[流行8]毕业季、回忆过去&追梦未来',url:'images/hot_rec/流行 (8).png'},
		],
		rock:[
			{describe:'[摇滚1]毕业季、回忆过去&追梦未来',url:'images/hot_rec/摇滚 (1).png'},
			{describe:'[摇滚2]毕业季、回忆过去&追梦未来',url:'images/hot_rec/摇滚 (2).png'},
			{describe:'[摇滚3]毕业季、回忆过去&追梦未来',url:'images/hot_rec/摇滚 (3).png'},
			{describe:'[摇滚4]毕业季、回忆过去&追梦未来',url:'images/hot_rec/摇滚 (4).png'},
			{describe:'[摇滚5]毕业季、回忆过去&追梦未来',url:'images/hot_rec/摇滚 (5).png'},
			{describe:'[摇滚6]毕业季、回忆过去&追梦未来',url:'images/hot_rec/摇滚 (6).png'},
			{describe:'[摇滚7]毕业季、回忆过去&追梦未来',url:'images/hot_rec/摇滚 (7).png'},
			{describe:'[摇滚8]毕业季、回忆过去&追梦未来',url:'images/hot_rec/摇滚 (8).png'},
		],
}
